# Candace Savonen Apr 2025 

name: Python Package CI

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]

jobs:
  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup UV and Python
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run: uv sync --all-extras --dev
      
      - name: Lint with ruff
        run: |
          uv pip install ruff
          ruff check .
      
      - name: Type check with mypy
        run: |
          uv pip install mypy
          mypy --disallow-untyped-defs --namespace-packages --explicit-package-bases src
          
      - name: Check formatting with black
        run: |
          uv pip install black
          black --check .

  test:
    name: Test Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup UV and Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: uv sync --all-extras --dev
      
      - name: Run tests with pytest
        run: |
          uv pip install pytest pytest-cov
          pytest --cov=./ --cov-report=xml

  build:
    name: Build Package
    runs-on: ubuntu-latest
    needs: [test]  
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup UV and Python
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
      
      - name: Build package
        run: |
          uv pip install build
          python -m build
      
      - name: Store built package
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
          retention-days: 7

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup UV and Python
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run: |
          # Sync with uv
          uv sync --all-extras --dev 
          uv pip install sphinx sphinx-rtd-theme
      
      - name: Build documentation
        run: |
          cd docs
          make html
      
