# Candace Jan 2025

name: Python package

on:
  pull_request:
    branches: [ main, staging ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # A dependency, gensim, does not play nice with 3.13 so as of 4-23-25 
        # this package is not compatible with 3.13
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: | 
          uv pip install pytest 
          pytest tests/test_metadatamachine.py -k "parse"
